extends "res://tests/test_case.gd"

const SCENE_CONTEXT_TOOL_PATH := "res://tools/player_rig_preview/export_player_rig_scene_context.py"

func run() -> Array[String]:
	assert_true(FileAccess.file_exists(SCENE_CONTEXT_TOOL_PATH), "Player rig scene-context preview tool must exist")
	if not FileAccess.file_exists(SCENE_CONTEXT_TOOL_PATH):
		return get_failures()

	var source := FileAccess.get_file_as_string(SCENE_CONTEXT_TOOL_PATH)
	assert_true(source.find("DEFAULT_OUTPUT = Path(\"/tmp/andry_player_rig_scene_context.png\")") != -1, "Scene-context preview must default outside the repository")
	assert_true(source.find("BEHIND_OBJECT_Z = 1") != -1, "Scene-context preview must keep a behind-player probe object")
	assert_true(source.find("PLAYER_ROOT_Z = 2") != -1, "Scene-context preview must render the player above behind-player objects")
	assert_true(source.find("FOREGROUND_OBJECT_Z = 10") != -1, "Scene-context preview must keep a foreground occluder probe")
	assert_true(source.find("BEHIND_DOOR_TEXTURE") != -1 and source.find("DoorBasic.png") != -1, "Scene-context preview must use a real door asset behind the player")
	assert_true(source.find("FOREGROUND_CHAIR_TEXTURE") != -1 and source.find("ChairBedroom.png") != -1, "Scene-context preview must use a real foreground object")
	assert_true(source.find("PLAYER_ROOT_Z + int(visual[\"z_index\"])") != -1, "Scene-context preview must sort individual player visuals by effective z-index")
	assert_true(source.find("_build_godot_dump_script") != -1, "Scene-context preview must sample real Godot skeleton transforms")
	assert_true(source.find("--flashlight") != -1, "Scene-context preview must support the flashlight variant")
	assert_true(source.find("--dark-closeup") != -1, "Scene-context preview must support screenshot-like dark close-up QA")
	assert_true(source.find("--pose-animation") != -1 and source.find("--pose-time") != -1, "Scene-context preview close-up must allow selecting an exact sampled animation frame")
	assert_true(source.find("DARK_CLOSEUP_PLAYER_SCALE") != -1, "Scene-context preview must keep a larger close-up player scale for dark-frame QA")
	assert_true(source.find("--layer-overlay") != -1, "Scene-context preview must support colored layer overlays for cutout diagnosis")
	assert_true(source.find("LAYER_OVERLAY_COLORS") != -1, "Scene-context preview must keep stable colors for Visual* layer diagnosis")
	var montage_source := FileAccess.get_file_as_string("res://tools/player_rig_preview/export_player_rig_montage.py")
	assert_true(montage_source.find("VisualFrontHandEmpty") != -1, "Rig preview dump must switch the empty-hand cutout for no-flashlight previews")
	assert_true(montage_source.find("held_hand.visible = show_flashlight") != -1, "Rig preview dump must show the held hand only with flashlight preview poses")
	assert_true(montage_source.find("--rig-path") != -1, "Rig preview montage must support sampling isolated prototype rigs")
	assert_true(montage_source.find("--animation-player-path") != -1, "Rig preview montage must support prototype AnimationPlayer node paths")
	assert_true(montage_source.find("--runtime-motion-set") != -1, "Rig preview montage must export runtime-real no-flashlight and flashlight motion states")
	assert_true(montage_source.find("\"light_walk\": 0.8") != -1, "Rig preview montage must know the light_walk animation length")
	assert_true(montage_source.find("\"run\": 0.55") != -1, "Rig preview montage must know the no-flashlight run animation length")
	assert_true(montage_source.find("\"light_walk\", 0.2, True") != -1, "Rig preview runtime set must include flashlight light_walk poses")
	assert_true(montage_source.find("\"run\", 0.1375, False") != -1, "Rig preview runtime set must include no-flashlight run poses")
	assert_true(montage_source.find("\"show_flashlight\"") != -1, "Rig preview montage must support per-pose flashlight visibility")
	assert_true(montage_source.find("Polygon2D") != -1, "Rig preview montage must sample weighted Polygon2D mesh visuals")
	assert_true(montage_source.find("_polygon_bone_rows") != -1, "Rig preview montage must export Polygon2D bone weights for visual QA")
	assert_true(montage_source.find("_render_polygon_visual") != -1, "Rig preview montage must render weighted mesh visuals, not only Sprite2D cutouts")
	assert_true(source.find("_render_visual_layer") != -1, "Scene-context preview must render visual layers through the shared Sprite2D/Polygon2D path")
	return get_failures()
